// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadOption describes one downloadable file listed in the Download
 * section of a trainer detail page.
 */
export interface DownloadOption {
    "group": string;
    "name": string;
    "url": string;
    "dateAdded": string;
    "fileSize": string;
    "downloads": string;
}

/**
 * SearchResult describes one trainer returned by the search agent.
 */
export interface SearchResult {
    "title": string;
    "url": string;
    "version": string;
    "updated": string;
    "options": string;
}

/**
 * TrainerDetail contains the metadata needed to render a trainer detail page.
 */
export interface TrainerDetail {
    "title": string;
    "gameVersion": string;
    "lastUpdated": string;
    "options": string[] | null;
    "images": string[] | null;
    "downloadUrl": string;
    "downloadOptions": DownloadOption[] | null;
    "description": string;
    "sourceUrl": string;
}
