// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TrainerService from "./trainerservice.js";
export {
    TrainerService
};

export type {
    DownloadProgress
} from "./models.js";
