// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress is emitted while a trainer archive is being downloaded.
 */
export interface DownloadProgress {
    "percent": number;
    "speed": string;
}
