// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrainerService exposes trainer search, detail parsing, and downloading to
 * the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DownloadTrainer downloads a trainer archive and emits download progress.
 */
export function DownloadTrainer(downloadURL: string): $CancellablePromise<string> {
    return $Call.ByID(794309322, downloadURL);
}

/**
 * GetTrainerDetail parses a trainer detail page.
 */
export function GetTrainerDetail(detailURL: string): $CancellablePromise<models$0.TrainerDetail | null> {
    return $Call.ByID(1909682945, detailURL);
}

/**
 * SearchTrainer searches FLiNG for trainers matching gameName.
 */
export function SearchTrainer(gameName: string): $CancellablePromise<models$0.SearchResult[] | null> {
    return $Call.ByID(3215967002, gameName);
}
